SELECT top 1* FROM categorias
SELECT top 1 * FROM productos

select * from pedidos

CREATE FUNCTION FN_Pedidos (
@idcliente varchar(10)
)
RETURNS TABLE
AS
	RETURN (SELECT C.IdCliente, COUNT(*) as NumPedidos FROM pedidos P INNER JOIN clientes C ON (P.IdCliente=C.IdCliente)
		WHERE C.IdCliente=@idcliente GROUP BY C.IdCliente)

SELECT * FROM FN_Pedidos('ALFAA')
go

CREATE FUNCTION FN_MINUTO(
@hora int,
@minuto int
)
RETURNS int
AS
BEGIN
	declare @minutos int
	SET @minutos = (@hora*60 + @minuto)
	RETURN @minutos
END
		
-- CREAR UNA FUNCION QUE PERMITA  ASIGNAR 	-- VALORES A UNA FECHA (MESES)	SELECT IdPedido	 ,fechapedido,			choose(month(fechapedido),	'ENERO',	'FEBRERO',	'MARZO',	'ABRIL',	'MAYO',	'JUNIO',	'JULIO',	'AGOSTO',	'SEPTIEMBRE',	'OCTUBRE',	'NOVIEMBRE',	'DICIEMBRE') as MES			FROM pedidos p


			--CREAR UNA FUNCION QUE DEVUELVA UN PORCENTAJE ingresado		-- A TODOS LOS PRODUCTOS DE UNA CATEGORIA DADACREATE FUNCTION FN_PRODUCTO_DESCUENTO(@CATEGORIA VARCHAR(20),@DESCUENTO numeric(4,2))RETURNS TABLEASRETURN(	SELECT P.NombreProducto,p.PrecioUnitario , c.NombreCategoria,	iif(c.NombreCategoria=@CATEGORIA,p.PrecioUnitario * @DESCUENTO,0) as descuento	FROM productos p	inner join categorias c on p.IdCategoria = c.IdCategoria);SELECT * FROM FN_PRODUCTO_DESCUENTO('Bebidas',0.10)


--CANTIDAD DE AÑOS DE LOS EMPLEADOS 

SELECT nombre, (YEAR(GETDATE()) - year(FechaNacimiento)) as año_nacimiento FROM empleados

--CANTIDAD DE AÑOS DE CONTRATADO

SELECT nombre, DATEDIFF(year,Fechacontratacion,GETDATE()) as año_contratacion FROM empleados


--FUNCIONES DE CADENA DE TEXTO
SELECT NOMBRE +SPACE(10)+Apellido FROM empleados

SELECT (nombre + SPACE(3) + Apellido) as nombres into Tabla1 FROM empleados


SELECT LEFT(nombres,CHARINDEX('',nombres)), SUBSTRING(nombres,CHARINDEX('',nombres),20) from Tabla1


-- FUNCIONES DE CADENA DE TEXTOSELECT NOMBRE +SPACE(10)+Apellido FROM empleados--SELECT INTOSELECT   (NOMBRE +SPACE(1)+Apellido) AS NOMBRES INTO TABLA3FROM empleados  --CHARINDEX  - DEVUELVE LA POSICION DE UN CARACTER--SUBSTRING  DEVUELVE UNA CADENA DE CARACTERES DESDE UNA POSICION INICIAL-- HASTA UNA FINALSELECT LEFT(NOMBRES,CHARINDEX(' ',NOMBRES)),SUBSTRING(NOMBRES,CHARINDEX(' ',NOMBRES),20) FROM TABLA3;

CREATE TABLE DATOS(			NOMBRES VARCHAR(50)			);INSERT INTO DATOS VALUES('JUANA VARGAZ MENDEZ')SELECT * FROM DATOS--DEVOLVER EL NOMBRESELECT LEFT(NOMBRES,CHARINDEX(' ',NOMBRES))FROM DATOS;--DEVOLVER EL PATERNOSELECT SUBSTRING(NOMBRES,CHARINDEX(' ',NOMBRES),CHARINDEX(' ',NOMBRES,CHARINDEX(' ',NOMBRES)+1)-CHARINDEX(' ',NOMBRES))FROM DATOS;--DEVOLVER EL MATERNOSELECT SUBSTRING(NOMBRES,CHARINDEX(' ',NOMBRES,CHARINDEX(' ',NOMBRES)+1),20) FROMDATOS;
