CREATE TABLE notas (Id int IDENTITY NOT NULL, registro_detalleId int NOT NULL, N1 int NULL, N2 int NULL, N3 int NULL, N4 int NULL, N5 int NULL, Ex1 int NULL, N7 int NULL, N8 int NULL, N9 int NULL, N10 int NULL, N11 int NULL, Ex2 int NULL, PRIMARY KEY (Id));
CREATE TABLE registro (Id int IDENTITY NOT NULL, profesorid int NOT NULL, programacion_horariaId int NOT NULL, marcaId int NOT NULL, cursoId int NOT NULL, Fecha_inicial datetime NULL, Fecha_final datetime NULL, Turno varchar(255) NULL, Entregado varchar(255) NULL, PRIMARY KEY (Id));
CREATE TABLE usuario (Id int IDENTITY NOT NULL, Paterno varchar(255) NULL, Materno varchar(255) NULL, Nombres varchar(255) NULL, Email varchar(255) NULL, Password varchar(255) NULL, Contrato varchar(255) NULL, Discriminator varchar(255) NOT NULL, Fecha_nacimiento datetime NULL, Numero_documento varchar(255) NULL, Ruc varchar(255) NULL, Telefono varchar(255) NULL, Celular varchar(255) NULL, Foto int NULL, Fec_reg datetime NULL, Fec_mod int NULL, PRIMARY KEY (Id));
CREATE TABLE registro_detalle (Id int IDENTITY NOT NULL, registroId int NOT NULL, moduloId int NOT NULL, estudianteId int NOT NULL, Fec_reg datetime NULL, Fec_mod datetime NULL, carrera_profesionalId int NOT NULL, PRIMARY KEY (Id));
CREATE TABLE asistencia (Id int IDENTITY NOT NULL, registro_detalleId int NOT NULL, Fecha datetime NULL, Estado varchar(255) NULL, PRIMARY KEY (Id));
CREATE TABLE curso (Id int IDENTITY NOT NULL, Descripcion varchar(255) NULL, Creditos int NOT NULL, Horas_semana int NOT NULL, Ciclo varchar(255) NULL, PRIMARY KEY (Id));
CREATE TABLE carrera_profesional (Id int IDENTITY NOT NULL, Descripcion varchar(255) NULL, PRIMARY KEY (Id));
CREATE TABLE programacion_horaria (Id int IDENTITY NOT NULL, Hora_inicial datetime NULL, Hora_final datetime NULL, Descripcion varchar(255) NULL, PRIMARY KEY (Id));
CREATE TABLE examen (Id int IDENTITY NOT NULL, usuarioId2 int NOT NULL, cursoId int NOT NULL, usuarioId int NOT NULL, Pregunta varchar(255) NULL, A varchar(255) NULL, B varchar(255) NULL, C varchar(255) NULL, D varchar(255) NULL, E varchar(255) NULL, Respuesta varchar(255) NULL, PRIMARY KEY (Id));
CREATE TABLE evaluacion (Id int IDENTITY NOT NULL, teacherId int NOT NULL, examenId int NOT NULL, Respuesta varchar(255) NULL, Estado varchar(255) NULL, Fec_reg int NULL, PRIMARY KEY (Id));
CREATE TABLE marca (Id int IDENTITY NOT NULL, Descripcion varchar(255) NULL, PRIMARY KEY (Id));
CREATE TABLE tema (Id int IDENTITY NOT NULL, profesorId int NOT NULL, cursoId int NOT NULL, Titulo varchar(255) NULL, Semana varchar(255) NULL, Contenido varchar(255) NULL, PRIMARY KEY (Id));
CREATE TABLE modulo (Id int IDENTITY NOT NULL, Descripcion varchar(255) NULL, PRIMARY KEY (Id));
ALTER TABLE registro_detalle ADD CONSTRAINT FKregistro_d775344 FOREIGN KEY (carrera_profesionalId) REFERENCES carrera_profesional (Id);
ALTER TABLE examen ADD CONSTRAINT FKexamen232787 FOREIGN KEY (usuarioId) REFERENCES usuario (Id);
ALTER TABLE examen ADD CONSTRAINT FKexamen594893 FOREIGN KEY (cursoId) REFERENCES curso (Id);
ALTER TABLE examen ADD CONSTRAINT FKexamen409561 FOREIGN KEY (usuarioId2) REFERENCES usuario (Id);
ALTER TABLE registro ADD CONSTRAINT FKregistro795700 FOREIGN KEY (cursoId) REFERENCES curso (Id);
ALTER TABLE evaluacion ADD CONSTRAINT FKevaluacion670484 FOREIGN KEY (examenId) REFERENCES examen (Id);
ALTER TABLE evaluacion ADD CONSTRAINT FKevaluacion36162 FOREIGN KEY (teacherId) REFERENCES usuario (Id);
ALTER TABLE registro ADD CONSTRAINT FKregistro463389 FOREIGN KEY (marcaId) REFERENCES marca (Id);
ALTER TABLE registro ADD CONSTRAINT FKregistro518367 FOREIGN KEY (programacion_horariaId) REFERENCES programacion_horaria (Id);
ALTER TABLE registro ADD CONSTRAINT FKregistro429200 FOREIGN KEY (profesorid) REFERENCES usuario (Id);
ALTER TABLE registro_detalle ADD CONSTRAINT FKregistro_d693424 FOREIGN KEY (estudianteId) REFERENCES usuario (Id);
ALTER TABLE notas ADD CONSTRAINT FKnotas464537 FOREIGN KEY (registro_detalleId) REFERENCES registro_detalle (Id);
ALTER TABLE asistencia ADD CONSTRAINT FKasistencia488686 FOREIGN KEY (registro_detalleId) REFERENCES registro_detalle (Id);
ALTER TABLE tema ADD CONSTRAINT FKtema565500 FOREIGN KEY (cursoId) REFERENCES curso (Id);
ALTER TABLE tema ADD CONSTRAINT FKtema660392 FOREIGN KEY (profesorId) REFERENCES usuario (Id);
ALTER TABLE registro_detalle ADD CONSTRAINT FKregistro_d998804 FOREIGN KEY (moduloId) REFERENCES modulo (Id);
ALTER TABLE registro_detalle ADD CONSTRAINT FKregistro_d730727 FOREIGN KEY (registroId) REFERENCES registro (Id);
